// export const db = async () => await (await fetch('https://dummyjson.com/todos?limit=150')).json()
import { writable, type Writable } from 'svelte/store'

type todo = {
	id: number
	todo: string
	completed: boolean
	// priority: 0 | 1 | 2 | 3
}

// export const db: Writable<{ todos: todo[] }> = writable({
// 	todos: [
// 		{ id: 1, todo: 'Do something nice for someone I care about', completed: true },
// 		{ id: 2, todo: 'Memorize the fifty states and their capitals', completed: false },
// 		{ id: 3, todo: 'Watch a classic movie', completed: false },
// 		{
// 			id: 4,
// 			todo: 'Contribute code or a monetary donation to an open-source software project',
// 			completed: false
// 		},
// 		{ id: 5, todo: "Solve a Rubik's cube", completed: false },
// 		{ id: 6, todo: 'Bake pastries for me and neighbor', completed: false },
// 		{ id: 7, todo: 'Go see a Broadway production', completed: false },
// 		{
// 			id: 8,
// 			todo: 'Write a thank you letter to an influential person in my life',
// 			completed: true
// 		},
// 		{ id: 9, todo: 'Invite some friends over for a game night', completed: false },
// 		{ id: 10, todo: 'Have a football scrimmage with some friends', completed: false },
// 		{ id: 11, todo: "Text a friend I haven't talked to in a long time", completed: false },
// 		{ id: 12, todo: 'Organize pantry', completed: true },
// 		{ id: 13, todo: 'Buy a new house decoration', completed: false },
// 		{ id: 14, todo: "Plan a vacation I've always wanted to take", completed: false },
// 		{ id: 15, todo: 'Clean out car', completed: false },
// 		{ id: 16, todo: 'Draw and color a Mandala', completed: true },
// 		{ id: 17, todo: 'Create a cookbook with favorite recipes', completed: false },
// 		{ id: 18, todo: 'Bake a pie with some friends', completed: false },
// 		{ id: 19, todo: 'Create a compost pile', completed: true },
// 		{ id: 20, todo: 'Take a hike at a local park', completed: true },
// 		{ id: 21, todo: 'Take a class at local community center that interests you', completed: false },
// 		{ id: 22, todo: 'Research a topic interested in', completed: false },
// 		{ id: 23, todo: 'Plan a trip to another country', completed: true },
// 		{ id: 24, todo: 'Improve touch typing', completed: false },
// 		{ id: 25, todo: 'Learn Express.js', completed: false },
// 		{ id: 26, todo: 'Learn calligraphy', completed: false },
// 		{ id: 27, todo: 'Have a photo session with some friends', completed: false },
// 		{ id: 28, todo: 'Go to the gym', completed: false },
// 		{ id: 29, todo: 'Make own LEGO creation', completed: false },
// 		{ id: 30, todo: 'Take cat on a walk', completed: false },
// 		{ id: 31, todo: 'Find a charity and donate to it', completed: true },
// 		{ id: 32, todo: 'Donate to local food bank', completed: true },
// 		{ id: 33, todo: 'Uninstall unused apps from devices', completed: false },
// 		{ id: 34, todo: 'Write a handwritten letter to somebody', completed: false },
// 		{ id: 35, todo: 'Fill out a basketball bracket', completed: false },
// 		{ id: 36, todo: 'Do yoga', completed: false },
// 		{ id: 37, todo: 'Make a scrapbook with pictures of favorite memories', completed: false },
// 		{ id: 38, todo: 'Have a bonfire with close friends', completed: true },
// 		{ id: 39, todo: 'Go for a run', completed: false },
// 		{ id: 40, todo: 'Host a movie marathon with some friends', completed: false },
// 		{ id: 41, todo: 'Go see a movie in theaters with a few friends', completed: true },
// 		{ id: 42, todo: 'Wash car', completed: false },
// 		{ id: 43, todo: 'Patronize a local independent restaurant', completed: false },
// 		{ id: 44, todo: 'Watch a Khan Academy lecture on a subject of choosing', completed: false },
// 		{ id: 45, todo: 'Learn Javascript', completed: false },
// 		{ id: 46, todo: 'Volunteer at a local animal shelter', completed: false },
// 		{ id: 47, todo: 'Volunteer at local food pantry', completed: false },
// 		{ id: 48, todo: "Start a book I've never gotten around to reading", completed: false },
// 		{ id: 49, todo: "Mow neighbor's lawn", completed: false },
// 		{ id: 50, todo: 'Start a band', completed: false },
// 		{ id: 51, todo: 'Organize music collection', completed: false },
// 		{ id: 52, todo: 'Organize a cluttered drawer', completed: true },
// 		{ id: 53, todo: 'Learn a new recipe', completed: true },
// 		{ id: 54, todo: 'Start a daily journal', completed: false },
// 		{ id: 55, todo: "Clean out closet and donate the clothes I've outgrown", completed: true },
// 		{ id: 56, todo: 'Go on a fishing trip with some friends', completed: false },
// 		{ id: 57, todo: 'Learn Morse code', completed: false },
// 		{ id: 58, todo: 'Listen to a new podcast', completed: true },
// 		{ id: 59, todo: 'Color', completed: false },
// 		{ id: 60, todo: 'Take dog on a walk', completed: true },
// 		{ id: 61, todo: "Start a blog for something I'm passionate about", completed: false },
// 		{ id: 62, todo: 'Listen to a new music genre', completed: false },
// 		{ id: 63, todo: 'Learn how to write in shorthand', completed: false },
// 		{ id: 64, todo: 'Practice coding in favorite language', completed: false },
// 		{ id: 65, todo: 'Read a formal research paper on an interesting subject', completed: true },
// 		{ id: 66, todo: 'Learn how to whistle with fingers', completed: true },
// 		{ id: 67, todo: 'Make a couch fort', completed: false },
// 		{ id: 68, todo: 'Take a caffeine nap', completed: false },
// 		{ id: 69, todo: 'Find a DIY to do', completed: false },
// 		{ id: 70, todo: 'Go to a concert with some friends', completed: false },
// 		{ id: 71, todo: 'Give pet ten minutes of focused attention', completed: false },
// 		{ id: 72, todo: 'Rearrange and organize room', completed: false },
// 		{ id: 73, todo: 'Learn how to play a new sport', completed: false },
// 		{ id: 74, todo: 'Make homemade ice cream', completed: true },
// 		{ id: 75, todo: 'Hold a yard sale', completed: true },
// 		{ id: 76, todo: 'Learn to play a new instrument', completed: false },
// 		{ id: 77, todo: "Resolve a problem I've been putting off", completed: true },
// 		{ id: 78, todo: "Bake something I've never tried before", completed: true },
// 		{ id: 79, todo: 'Organize dresser', completed: false },
// 		{ id: 80, todo: "Fix something that's broken in house", completed: false },
// 		{ id: 81, todo: 'Play a video game', completed: false },
// 		{ id: 82, todo: "Listen to music I haven't heard in a while", completed: false },
// 		{ id: 83, todo: 'Look at finances and find one way to save money', completed: false },
// 		{ id: 84, todo: 'Learn the periodic table', completed: true },
// 		{ id: 85, todo: 'Make a budget', completed: true },
// 		{ id: 86, todo: 'Donate blood at a local blood center', completed: false },
// 		{ id: 87, todo: 'Go to the library and find an interesting book', completed: false },
// 		{ id: 88, todo: 'Configure two-factor authentication on accounts', completed: false },
// 		{ id: 89, todo: 'Take a nap', completed: true },
// 		{ id: 90, todo: 'Create or update resume', completed: false },
// 		{ id: 91, todo: 'Prepare a 72-hour kit', completed: true },
// 		{ id: 92, todo: 'Go on a long drive with no music', completed: false },
// 		{ id: 93, todo: 'Learn the NATO phonetic alphabet', completed: false },
// 		{ id: 94, todo: 'Have a jam session with friends', completed: false },
// 		{ id: 95, todo: 'Hold a video game tournament with some friends', completed: false },
// 		{ id: 96, todo: 'Catch up on world news', completed: false },
// 		{ id: 97, todo: 'Do a jigsaw puzzle', completed: false },
// 		{ id: 98, todo: 'Learn about the Golden Ratio', completed: false },
// 		{ id: 99, todo: 'Organize basement', completed: true },
// 		{ id: 100, todo: 'Learn a new programming language', completed: true },
// 		{ id: 101, todo: 'Learn how the internet works', completed: false },
// 		{ id: 102, todo: 'Organize a bookshelf', completed: false },
// 		{ id: 103, todo: 'Go to a local thrift shop', completed: true },
// 		{ id: 104, todo: 'Study a foreign language', completed: true },
// 		{ id: 105, todo: 'Explore a park I have never been to before', completed: false },
// 		{ id: 106, todo: 'Start a garden', completed: true },
// 		{ id: 107, todo: "Shred old documents I don't need anymore", completed: false },
// 		{ id: 108, todo: 'Learn to write with nondominant hand', completed: true },
// 		{ id: 109, todo: 'Go to a nail salon', completed: false },
// 		{ id: 110, todo: 'Create a meal plan for the coming week', completed: true },
// 		{ id: 111, todo: 'Surprise significant other with something considerate', completed: false },
// 		{ id: 112, todo: 'Clean out garage', completed: false },
// 		{ id: 113, todo: 'Make a simple musical instrument', completed: false },
// 		{ id: 114, todo: 'Learn how to fold a paper crane', completed: true },
// 		{ id: 115, todo: 'Learn the Chinese erhu', completed: false },
// 		{ id: 116, todo: 'Start a family tree', completed: true },
// 		{ id: 117, todo: 'Teach dog a new trick', completed: true },
// 		{ id: 118, todo: 'Draw something interesting', completed: false },
// 		{ id: 119, todo: 'Explore the nightlife of city', completed: true },
// 		{ id: 120, todo: 'Make tie dye shirts', completed: false },
// 		{ id: 121, todo: 'Think of a new business idea', completed: true },
// 		{ id: 122, todo: 'Go swimming with a friend', completed: false },
// 		{ id: 123, todo: 'Clean out refrigerator', completed: true },
// 		{ id: 124, todo: 'Pot some plants and put them around house', completed: false },
// 		{ id: 125, todo: 'Learn how to beatbox', completed: false },
// 		{ id: 126, todo: 'Take a bubble bath', completed: true },
// 		{ id: 127, todo: 'Prepare a dish from a foreign culture', completed: false },
// 		{ id: 128, todo: 'Paint the first thing I see', completed: false },
// 		{ id: 129, todo: 'Learn how to use a french press', completed: false },
// 		{
// 			id: 130,
// 			todo: 'Learn about a distributed version control system such as Git',
// 			completed: true
// 		},
// 		{ id: 131, todo: 'Learn GraphQL', completed: false },
// 		{ id: 132, todo: 'Learn origami', completed: false },
// 		{ id: 133, todo: 'Go to a karaoke bar with some friends', completed: true },
// 		{ id: 134, todo: 'Conquer one of fears', completed: false },
// 		{ id: 135, todo: 'Shop at support local farmers market', completed: false },
// 		{ id: 136, todo: 'Compliment someone', completed: false },
// 		{ id: 137, todo: 'Do something I used to do as a kid', completed: false },
// 		{ id: 138, todo: 'Match storage containers with their lids', completed: false },
// 		{ id: 139, todo: 'Learn Kotlin', completed: false },
// 		{ id: 140, todo: 'Write a short story', completed: true },
// 		{ id: 141, todo: 'Visit a nearby museum', completed: true },
// 		{ id: 142, todo: 'Make a new friend', completed: false },
// 		{ id: 143, todo: 'Drink water', completed: false },
// 		{ id: 144, todo: 'Charge the phone', completed: false },
// 		{ id: 145, todo: 'Pay utility bills', completed: false },
// 		{ id: 146, todo: 'Make a JavaScript library', completed: false },
// 		{ id: 147, todo: 'Use DummyJSON', completed: false },
// 		{ id: 148, todo: 'Hug Mom :)', completed: false },
// 		{ id: 149, todo: 'Play cricket', completed: false },
// 		{ id: 150, todo: 'Sleeeeep for the whole day!!!', completed: false }
// 	]
// })

export const db: Writable<{ todos: todo[] }> = writable({ todos: [] })
